### ISSUE TITLE
sqlalchemy.exc.ArgumentError: Class 'MyClass' already has a primary mapper defined. 

### ISSUE THREAD

**Issue by federicoemartinez** [absent1706/sqlalchemy-mixins#107]
I have a project with SQLAlchemy 1.4 and sqlalchemy-mixins 1.5.3.
I have upgraded SQLAlchemy to 2.0 and made the code work and passes the tests. Then, I tried to upgrade sqlalchemy-mixins to 2.0.3 but I get the error of the title.

```
File "/lib/MyClass.py", line 12, in <module>
    class MyClass(MyBaseClass):
  File "/venv38/lib/python3.8/site-packages/sqlalchemy/orm/decl_api.py", line 195, in __init__
    _as_declarative(reg, cls, dict_)
  File "/venv38/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 247, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/venv38/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 328, in setup_mapping
    return _ClassScanMapperConfig(
  File "/venv38/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 520, in __init__
    super().__init__(registry, cls_, mapper_kw)
  File "/venv38/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 344, in __init__
    instrumentation.register_class(
  File "/venv38/lib/python3.8/site-packages/sqlalchemy/orm/instrumentation.py", line 684, in register_class
    manager._update_state(
  File "/venv38/lib/python3.8/site-packages/sqlalchemy/orm/instrumentation.py", line 209, in _update_state
    registry._add_manager(self)
  File "/venv38/lib/python3.8/site-packages/sqlalchemy/orm/decl_api.py", line 1380, in _add_manager
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Class '<class 'lib.MyClass'>' already has a primary mapper defined. 
```

MyBaseClass is defined as:

```python
class MyBaseClass(AnotherBaseClass):
    __abstract__ = True

    #SOME CODE

class AnotherBaseClass(Base, AllFeaturesMixin):
    __abstract__ = True

    #SOME OTHER CODE
```

Any idea of what may be happening or how to troubleshoot this?

**Comment by michaelbukachi** [comment]
Do you mind sharing a minimum reproducible snippet?

**Comment by federicoemartinez** [comment]
Sure!
This fails with 
SQLAlchemy==2.0.19 and sqlalchemy-mixins==2.0.3


```python
from sqlalchemy.orm import declarative_base
from sqlalchemy import Column, Integer
from sqlalchemy_mixins import AllFeaturesMixin
Base = declarative_base()

class MyOtherBaseClass(Base, AllFeaturesMixin):
    __abstract__ = True

class MyBaseClass(MyOtherBaseClass):
    __abstract__ = True

class Test(MyBaseClass):
    __tablename__ = 'test'
    id = Column(Integer(), primary_key=True)
```

```
Traceback (most recent call last):
  File "scratch_25.py", line 12, in <module>
    class Test(MyBaseClass):
  File "/venv38/lib/python3.8/site-packages/sqlalchemy/orm/decl_api.py", line 195, in __init__
    _as_declarative(reg, cls, dict_)
  File "/venv38/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 247, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/venv38/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 328, in setup_mapping
    return _ClassScanMapperConfig(
  File "/venv38/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 520, in __init__
    super().__init__(registry, cls_, mapper_kw)
  File "/venv38/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 344, in __init__
    instrumentation.register_class(
  File "/venv38/lib/python3.8/site-packages/sqlalchemy/orm/instrumentation.py", line 684, in register_class
    manager._update_state(
  File "/venv38/lib/python3.8/site-packages/sqlalchemy/orm/instrumentation.py", line 209, in _update_state
    registry._add_manager(self)
  File "/venv38/lib/python3.8/site-packages/sqlalchemy/orm/decl_api.py", line 1380, in _add_manager
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Class '<class '__main__.Test'>' already has a primary mapper defined. 
```

**Comment by michaelbukachi** [comment]
@federicoemartinez Do you mind testing against #108 ?

**Comment by federicoemartinez** [comment]
It works in #108 with both alternatives: with declarative_base and with class Base(DeclarativeBase)

**Comment by michaelbukachi** [comment]
`v2.0.4` should now be live
