### ISSUE TITLE
Inspection broken when used with sqlalchemy.ext.declarative.declarative_base

### ISSUE THREAD

**Issue by pdeblanc** [absent1706/sqlalchemy-mixins#13]
I tried to get help on a class that inherits from AllFeaturesMixin as well as some other classes. I've been able to reduce it to this small failing case:

```
from sqlalchemy import Column, Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy_mixins import AllFeaturesMixin

Base = declarative_base()

class Thing(Base, AllFeaturesMixin):
    __tablename__ = 'things'
    id = Column(Integer, primary_key=True)

help(Thing)
```

This results in the following failure:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_sitebuiltins.py", line 103, in __call__
    return pydoc.help(*args, **kwds)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 1895, in __call__
    self.help(request)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 1954, in help
    else: doc(request, 'Help on %s:', output=self._output)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 1674, in doc
    pager(render_doc(thing, title, forceload))
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 1667, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 386, in document
    if inspect.isclass(object): return self.docclass(*args)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 1312, in docclass
    for name, kind, cls, value in classify_class_attrs(object)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 209, in classify_class_attrs
    for (name, kind, cls, value) in inspect.classify_class_attrs(object):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 434, in classify_class_attrs
    srch_obj = getattr(srch_cls, name, None)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_mixins/utils.py", line 12, in __get__
    return self.fget(owner_cls)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_mixins/inspection.py", line 17, in columns
    return inspect(cls).columns.keys()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/inspection.py", line 75, in inspect
    type_)
sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'sqlalchemy.ext.declarative.api.DeclarativeMeta'>
```

**Comment by yuchixing** [comment]
HI, are you  resolve?

**Comment by absent1706** [comment]
Hi! Unfortunately, I don't have enough time for that now, maybe later.

------ Original Message ------
