### ISSUE TITLE
Duplicate bases fo classs

### ISSUE THREAD

**Issue by tatdatpham** [absent1706/sqlalchemy-mixins#23]
I found your lib from Internet, 
Im testing with some  your example .
[all_features.py](https://github.com/absent1706/sqlalchemy-mixins/blob/master/examples/all_features.py)
I got some warning (in vscode with pylint). Is that normaly ?

![image](https://user-images.githubusercontent.com/3429970/61428067-c805ad00-a94a-11e9-9736-c8ef23d2f327.png)

And in sqlalchemy,  i used __init__ for set some default value  like that

```
 class User(BaseModel):
    __tablename__ = 'users'
    id = Column(String(80), primary_key=True)
    username = Column(String(80))
    email = Column(String(80))
    password = Column(String(80))
    access_token = Column(Text)
    create_time = Column(DateTime)
    update_time = Column(DateTime)
    status = Column(Integer)

    def __init__(self, id, username, email, password, access_token=None, create_time=None, update_time=None, status=1):
        self.id = id
        self.username = username
        self.email = email
        self.password = password
        self.access_token = access_token
        if create_time is None:
            create_time = datetime.utcnow()
        if update_time is None:
            update_time = datetime.utcnow()
        self.create_time = create_time
        self.update_time = update_time
        self.status = status

    def __repr__(self):
        return '<Username %r>' % self.username
```

So in sqlalchemy-mixins, can i use init ? And how to use.
I call fun User.create() and got error :

```
[2019-07-18 12:44:52,157] ERROR in app: Exception on /api/auth/register [POST]
Traceback (most recent call last):
  File "/home/datpt/Documents/github/malbot/env/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/datpt/Documents/github/malbot/env/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/datpt/Documents/github/malbot/env/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/datpt/Documents/github/malbot/env/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/datpt/Documents/github/malbot/env/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/datpt/Documents/github/malbot/apis/auth/auth.py", line 61, in post
    User.create(username=data['username'],email=data['email'],password=sha256.hash(data['password']))
  File "/home/datpt/Documents/github/malbot/env/lib/python3.6/site-packages/sqlalchemy_mixins/activerecord.py", line 39, in create
    return cls().fill(**kwargs).save()
TypeError: __init__() missing 4 required positional arguments: 'id', 'username', 'email', and 'password'
10.15.154.23 - - [18/Jul/2019 12:44:52] "POST /api/auth/register HTTP/1.1" 500 -
```

**Comment by absent1706** [comment]
Hi @tatdatpham !
1. About warnings in VS code: quite strange, haven't ever met something like that...
2. `create()` method [invokes class creation and then fills all passed fields](https://github.com/absent1706/sqlalchemy-mixins/blob/master/sqlalchemy_mixins/activerecord.py#L34) . In your case, you can pass `id, username, email, password` (a-la required fields) to `create` method, like that
```python
User.create(id=1, username='bob', email='asd@gmail.com', password='123')
```
