### ISSUE TITLE
Smart query on m2m backref fails

### ISSUE THREAD

**Issue by maximdeclercq** [absent1706/sqlalchemy-mixins#39]
I have the following (simplified) model:

```
children_association = db.Table(
    'x_children',
    db.Column('parent_id', db.Integer, db.ForeignKey('x.id'), primary_key=True),
    db.Column('child_id', db.Integer, db.ForeignKey('x.id'), primary_key=True),
)

class X(BaseModel):
    id = db.Column(db.Integer, primary_key=True)
    slug = db.Column(db.String(256), index=True, unique=True, nullable=False, server_default='')
    
    children = db.relationship(
        'X',
        secondary=children_association,
        primaryjoin=id == children_association.c.parent_id,
        secondaryjoin=id == children_association.c.child_id,
        backref='parents',
    )

    def __repr__(self):
        return '<X %r>' % self.slug
```

But I can't query on parents (m2m backrefs), only on children:

```
X.where(children___slug='abc').first() # Works

X.where(parents___slug='abc').first() # Fails
Traceback (most recent call last):
   ... some unrelated stuff from my app
  File "./venv/lib/python3.8/site-packages/sqlalchemy_mixins/smartquery.py", line 343, in where
    return cls.smart_query(filters)
  File "./venv/lib/python3.8/site-packages/sqlalchemy_mixins/smartquery.py", line 327, in smart_query
    return smart_query(cls.query, filters, sort_attrs, schema)
  File "./venv/lib/python3.8/site-packages/sqlalchemy_mixins/smartquery.py", line 91, in smart_query
    _parse_path_and_make_aliases(root_cls, '', attrs, aliases)
  File "./venv/lib/python3.8/site-packages/sqlalchemy_mixins/smartquery.py", line 61, in _parse_path_and_make_aliases
    alias = aliased(relationship.property.argument())
```

**Comment by absent1706** [comment]
Fixed in https://github.com/absent1706/sqlalchemy-mixins/pull/40 , thanks, @maximdeclercq !
