### ISSUE TITLE
Error: sqlalchemy.exc.NoInspectionAvailable

### ISSUE THREAD

**Issue by vs-zhang** [absent1706/sqlalchemy-mixins#4]
Hi there,

thanks for this great package. I try to use your package  version `0.2.2` with sqlalchemy version `1.1.10` But got some errors from the InspectionMixin. Could you help me with this. Thanks

```
Traceback (most recent call last):
  File "/Users/Pei/code/myproject/services/auth/auth_env/bin/nameko", line 11, in <module>
    sys.exit(main())
  File "/Users/Pei/code/myproject/services/auth/auth_env/lib/python2.7/site-packages/nameko/cli/main.py", line 69, in main
    args.main(args)
  File "/Users/Pei/code/myproject/services/auth/auth_env/lib/python2.7/site-packages/nameko/cli/commands.py", line 85, in main
    main(args)
  File "/Users/Pei/code/myproject/services/auth/auth_env/lib/python2.7/site-packages/nameko/cli/run.py", line 178, in main
    import_service(path)
  File "/Users/Pei/code/myproject/services/auth/auth_env/lib/python2.7/site-packages/nameko/cli/run.py", line 70, in import_service
    if inspect.getmembers(potential_service, is_entrypoint):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/inspect.py", line 253, in getmembers
    value = getattr(object, key)
  File "/Users/Pei/code/myproject/services/auth/auth_env/lib/python2.7/site-packages/sqlalchemy_mixins/utils.py", line 12, in __get__
    return self.fget(owner_cls)
  File "/Users/Pei/code/myproject/services/auth/auth_env/lib/python2.7/site-packages/sqlalchemy_mixins/inspection.py", line 17, in columns
    return inspect(cls).columns.keys()
  File "/Users/Pei/code/myproject/services/auth/auth_env/lib/python2.7/site-packages/sqlalchemy/inspection.py", line 75, in inspect
    type_)
sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'sqlalchemy.ext.declarative.api.DeclarativeMeta'>
```

**Comment by absent1706** [comment]
Hello!
Please give your ORM class which is inspected.
